name: test_screenshot
description: Take screenshots during your flutter unit tests
version: 0.0.6
homepage: https://github.com/cedvdb/flutter_test_screenshot

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  image: ^4.3.0
  file: ^7.0.1
  platform: ^3.1.6

dev_dependencies:

  flutter_lints: ^5.0.0
